name: telegram-bot-actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-scp-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ./telegram-bot
      
    - name: Check file
      run: ls .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot
        path: ./telegram-bot
        retention-days: 5
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./telegram-bot"
        target: "${{secrets.TARGET_DIR}}"
        
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
        # hostname / IP of the server
        HOST: ${{ secrets.HOST }}
        # ssh port of the server
        PORT: ${{ secrets.PORT }}
        # user of the server
        USER: ${{ secrets.USERNAME }}
        # private ssh key registered on the server
        PRIVATE_SSH_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        # command to be executed
        COMMAND: source ~/.bash_profile && ${{ secrets.TARGET_DIR }}/deploy_telegram_bot.sh








