name: telegram-bot-actions

on:
  push:
    branches: [ "master" ]

jobs:

  build-scp-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ./telegram-bot
      
    - name: Check file
      run: ls .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot
        path: ./telegram-bot
        retention-days: 5
        
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@f9010ff7f1bbd7db1a0b4bab661437550cea20c0
      uses: appleboy/ssh-action@v0.1.5
      with:
        # ssh host
        host: ${{ secrets.HOST }}
        # ssh port
        port: ${{ secrets.PORT }}
        # ssh username
        username: ${{ secrets.USERNAME }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        # execute commands
        script: |
          source ~/.bash_profile
          cd ${{ secrets.TARGET_DIR }}
          nohup sh ./deploy_telegram_bot.sh & disown
          








