name: telegram-bot-actions

on:
  push:
    branches: [ "master" ]

jobs:

  build-scp-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ./telegram-bot-go
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot-go
        path: ./telegram-bot-go
        retention-days: 5
    
    - name: SCP Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
      uses: appleboy/scp-action@master
      with:
        # ssh host
        host: ${{ secrets.HOST }}
        # ssh port
        port: ${{ secrets.PORT }}
        # ssh username
        username: ${{ secrets.USERNAME }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        source: "./telegram-bot-go"
        target: ${{ secrets.TARGET_DIR }}/
        
    - name: SSH Execute Commands
      # You may pin to the exact commit or the version.
      # uses: JimCronqvist/action-ssh@1c03e01b4ac39da814b45cfd2924c2df0ff1396f
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        # Command(s) to execute on the remote server.
        command: |
          source ~/.bash_profile
          cd ${{ secrets.TARGET_DIR }}
          nohup sh telegram_bot.sh restart 2>&1 & ${{ secrets.TARGET_DIR }}/log/telegram_bot.std
        # Hostname or IP address of the remote server(s). Separate multiple servers with a blank space. Example: 'user@mydomain.com:22 user@otherdomain.com:2222'
        hosts: ${{ secrets.HOST }}:${{ secrets.PORT }}
        # The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret.
        privateKey: ${{ secrets.SERVER_PRIVATE_KEY }}
          
          
 








