name: telegram-bot-actions

on:
  push:
    branches: [ "master" ]

jobs:

  build-scp-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ./telegram-bot-go
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot-go
        path: ./telegram-bot-go
        retention-days: 5
    
    - name: SCP Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
      uses: appleboy/scp-action@master
      with:
        # ssh host
        host: ${{ secrets.HOST }}
        # ssh port
        port: ${{ secrets.PORT }}
        # ssh username
        username: ${{ secrets.USERNAME }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        source: "./telegram-bot-go"
        target: ${{ secrets.TARGET_DIR }}/
        
    - name: ssh-pipeline
      # You may pin to the exact commit or the version.
      # uses: cross-the-world/ssh-pipeline@7f022867934a210af826af99ef80d96f03a094d5
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        # ssh remote host
        host: ${{ secrets.HOST }}
        # ssh remote port
        port: ${{ secrets.PORT }}
        # ssh remote user
        user: ${{ secrets.USERNAME }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        # execute commands on ssh
        script: |
          source ~/.bash_profile
          cd ${{ secrets.TARGET_DIR }}
          sh telegram_bot.sh restart
          
          
 








