name: telegram-bot-actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ./telegram-bot-bin
      
    - name: Check file
      run: ls .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot
        path: ./telegram-bot-bin
        retention-days: 5
        
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{secrets.SERVER_PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: ${{secrets.HOST}}
        # Remote user
        REMOTE_USER: ${{secrets.USERNAME}}
        # Remote port
        REMOTE_PORT: ${{secrets.PORT}}
        # Source directory
        SOURCE: ./
        # Target directory
        TARGET: /home/${{secretes.USERNAME}}/utils/telegram-bot/


